### ISSUE TITLE
大佬，博客的 rss 订阅挂了。

### ISSUE THREAD

**Issue by moonD4rk** [mylamour/blog#77]
从你的博客学到了很多，感谢🙏

`https://iami.xyz/feed/` 能修一下么

**Comment by mylamour** [comment]
Hi, moonD4rk, 谢谢你的建议，不过最初好像就没有feed吧，应该有rss订阅软件是无需要feed即可直接订阅的。当然如果你watch或者star了这个repo的话，每次update可以收到邮件通知的。

// 另外下次这种问题可以邮件讨论

**Comment by moonD4rk** [comment]
好的，谢谢。

**Comment by mylamour** [comment]
pyGithub test.
